### ISSUE TITLE
"Template resource 'leiningen/new/thing_babel/readme.org' not found." when lein new thing-babel bar

### ISSUE THREAD

**Issue by yubrshen** [thi-ng/babel#2]
I got the following error:

$ lein new thing-babel bar
Generating fresh literate programming project: bar
generated project dir   : bar
artefact group ID       :
project url             : https://github.com/
project author          : B37747
author url              :
author email            :
author timezone         : 8
license                 : Eclipse Public License
description             : FIXME: write description
path for gen sources    : babel\
project root namespace  : bar
Template resource 'leiningen/new/thing_babel/readme.org' not found.

It's with the latest 0.3.1. 

It seems that Clojars is not yet updated of 0.3.1 - 2015-08-28

As I could overcome this problem by clone your repository, and then doing:

cd babel
lein install

**Comment by postspectacular** [comment]
Oh, looking over this just once more, I see that I misread your report earlier. Due to OSX not being case-sensitive this has completely escaped my testing. Thanks! v0.3.2.1 should fix this (just pushed to clojars)

**Comment by yubrshen** [comment]
Hi Karsten,

I'm afraid that the problem was not fixed. Here is the negative result of
verification:

$ lein new thing-babel bar
Retrieving thing-babel/lein-template/0.3.2.1/lein-template-0.3.2.1.pom from
clojars
Retrieving thing-babel/lein-template/0.3.2.1/lein-template-0.3.2.1.jar from
clojars
Generating fresh literate programming project: bar
generated project dir   : bar
artefact group ID       :
project url             : https://github.com/
project author          : B37747
author url              :
author email            :
author timezone         : 8
license                 : Eclipse Public License
description             : FIXME: write description
path for gen sources    : babel/
project root namespace  : bar
Template resource 'leiningen/new/thing_babel/readme.org' not found.

It's a problem with creating the template, not with tangle-all.sh. So it
seems that your fix to the issue may not address the real issue.

It looks that I'm using your new update:
Retrieving thing-babel/lein-template/0.3.2.1/lein-template-0.3.2.1.pom from
clojars
Retrieving thing-babel/lein-template/0.3.2.1/lein-template-0.3.2.1.jar from
clojars
--
Again, the clue might still with the fact that when I clone your
repository, and build the library locally, then it worked, as the following
trace shows:

B37747@B37747-11 ~/dev/clojure
$ git clone https://github.com/thi-ng/babel
Cloning into 'babel'...
remote: Counting objects: 202, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 202 (delta 14), reused 0 (delta 0), pack-reused 157
Receiving objects: 100% (202/202), 42.51 KiB | 34.00 KiB/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.

B37747@B37747-11 ~/dev/clojure
$ cd babel

B37747@B37747-11 ~/dev/clojure/babel
$ lein install
Created D:\yushen\dev\clojure\babel\target\lein-template-0.3.2.1.jar
Wrote D:\yushen\dev\clojure\babel\pom.xml
Installed jar and pom into local repo.

B37747@B37747-11 ~/dev/clojure/babel
$ cd ..

B37747@B37747-11 ~/dev/clojure
$ lein new thing-babel bar
Generating fresh literate programming project: bar
generated project dir   : bar
artefact group ID       :
project url             : https://github.com/
project author          : B37747
author url              :
author email            :
author timezone         : 8
license                 : Eclipse Public License
description             : FIXME: write description
path for gen sources    : babel/
project root namespace  : bar

B37747@B37747-11 ~/dev/clojure
----

Thanks,

Yu

**Comment by postspectacular** [comment]
There's some discrepancy between git being case sensitive and OSX isn't. So I renamed the readme template file and this hopefully fixes it (pushed 3.2.2.2 to clojars). Thanks for testing/reporting this!

**Comment by yubrshen** [comment]
@Karsten, yes, it's fixed! Thanks! Yu

**Comment by postspectacular** [comment]
Great! :)
